# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c898a0717dc4796874ed2a70b7019c432079d289a86a41b997082cf2ac87d53fdb10082f09b7bbafdd109f3ca3c9c2417ebb860a76809306e63b247f9281157

test:
  secret_key_base: 601510ab2e2a375febd8583344a05d647a3c78319084f0b21f48f94c145eb326ce03b1609f550fd26b831cae908b208782ed29a17e07e4aea5be1dcebdaf2419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
